pipeline {
    agent any
    parameters {
        string(name: 'buildControlFlag', defaultValue: 'success', description: 'fail in build stage: build, fail in test stage: test')
    }
    stages {
        stage('Build') {
            steps {
                script {
                    if (params.buildControlFlag == 'build') {
                        error "build has failed!"
                    }
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    if (params.buildControlFlag == 'test') {
                        error "test has failed!"
                    }
                }
            }
        }
    }
    post {
        success {
            mqttNotification brokerUrl: 'tcp://broker.hivemq.com:1883', credentialsId: '', message: '00', qos: '0', topic: 'build-monitor/build-status'
        }
        failure {
            mqttNotification brokerUrl: 'tcp://broker.hivemq.com:1883', credentialsId: '', message: '01', qos: '0', topic: 'build-monitor/build-status'
        }
    }
}