pipeline {
    agent any
    parameters {
        string(name: 'buildControlFlag', defaultValue: 'success', description: 'fail in build stage: build, fail in test stage: test')
    }
    stages {
        stage('Build') {
            steps {
                script {
                    if (${params.buildControlFlag} == 'build') {
                       mqttNotification {
                           brokerUrl "mqtt://broker.hivemq.com"
                           topic "build-monitor/build-status"
                           message "01"
                       }
                       error "build has failed!"
                    }
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    if (${params.buildControlFlag} == 'test') {
                       mqttNotification {
                           brokerUrl "mqtt://broker.hivemq.com"
                           topic "build-monitor/build-status"
                           message "01"
                       }
                       error "test has failed!"
                    }
                }
            }
        }
    }
}